name: Stayin' Alive
on:
  schedule:
    - cron: "0 0 * * *"
permissions:
  actions: write
jobs:
  keepalive:
    name: Keep It Goin'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
